-- -- Seed data from parks.json
-- -- Auto-generated by generate_seed.py
-- -- DO NOT EDIT THIS FILE MANUALLY - regenerate using: python3 database/generate_seed.py

-- BEGIN;

-- INSERT INTO parks (id, name, park_code, park_url, state_code, latitude, longitude) VALUES (1, 'Adeline Jay Geo-Karis Illinois Beach State Park', 'adeline-jay-geo-karis-illinois-beach', NULL, 'IL', 42.466, -87.81);
-- INSERT INTO activities (park_id, name, description) VALUES (1, 'Bike Trails', '');
-- INSERT INTO activities (park_id, name, description) VALUES (1, 'Camping', '');
-- INSERT INTO activities (park_id, name, description) VALUES (1, 'Cross Country Skiing', '');
-- INSERT INTO activities (park_id, name, description) VALUES (1, 'Fishing', '');
-- INSERT INTO activities (park_id, name, description) VALUES (1, 'Geocaching', '');
-- INSERT INTO activities (park_id, name, description) VALUES (1, 'Hiking Trails', '');
-- INSERT INTO activities (park_id, name, description) VALUES (1, 'SCUBA Diving', '');
-- INSERT INTO activities (park_id, name, description) VALUES (1, 'Swimming', '');

-- INSERT INTO parks (id, name, park_code, park_url, state_code, latitude, longitude) VALUES (2, 'Anderson Lake SFWA', 'anderson-lake-sfwa-il', null, 'IL', 40.19, -90.213);
-- INSERT INTO activities (park_id, name, description) VALUES (2, 'Boating', '');
-- INSERT INTO activities (park_id, name, description) VALUES (2, 'Camping', '');
-- INSERT INTO activities (park_id, name, description) VALUES (2, 'Fishing', '');
-- INSERT INTO activities (park_id, name, description) VALUES (2, 'Hunting', '');
-- INSERT INTO activities (park_id, name, description) VALUES (2, 'Picnicking', '');

-- INSERT INTO parks (id, name, park_code, park_url, state_code, latitude, longitude) VALUES (3, 'Apple River Canyon State Park', 'apple-river-canyon-state-park-il' , null, 'IL', 42.448, -90.043);
-- INSERT INTO activities (park_id, name, description) VALUES (3, 'Camping', '');
-- INSERT INTO activities (park_id, name, description) VALUES (3, 'Fishing', '');
-- INSERT INTO activities (park_id, name, description) VALUES (3, 'Hiking Trails', '');
-- INSERT INTO activities (park_id, name, description) VALUES (3, 'Hunting', '');
-- INSERT INTO activities (park_id, name, description) VALUES (3, 'Picnicking', '');

-- INSERT INTO parks (id, name, park_code, park_url, state_code, latitude, longitude) VALUES (4, 'Argyle Lake State Park', 'argyle-lake-state-park-il', null, 'IL', 40.449, -90.803);
-- INSERT INTO activities (park_id, name, description) VALUES (4, 'Archery Range', '');
-- INSERT INTO activities (park_id, name, description) VALUES (4, 'Boating', '');
-- INSERT INTO activities (park_id, name, description) VALUES (4, 'Camping', '');
-- INSERT INTO activities (park_id, name, description) VALUES (4, 'Equestrian Trails', '');
-- INSERT INTO activities (park_id, name, description) VALUES (4, 'Fishing', '');
-- INSERT INTO activities (park_id, name, description) VALUES (4, 'Hiking Trails', '');
-- INSERT INTO activities (park_id, name, description) VALUES (4, 'Hunting', '');
-- INSERT INTO activities (park_id, name, description) VALUES (4, 'Metal Detecting', '');
-- INSERT INTO activities (park_id, name, description) VALUES (4, 'Mountain Bike Trails', '');
-- INSERT INTO activities (park_id, name, description) VALUES (4, 'SCUBA Diving', '');
-- INSERT INTO activities (park_id, name, description) VALUES (4, 'Shelter Reservations', '');
-- INSERT INTO activities (park_id, name, description) VALUES (4, 'Snowmobile Trails', '');

-- INSERT INTO parks (id, name, park_code, park_url, state_code, latitude, longitude) VALUES (5, 'Banner Marsh State Fish and Wildlife Area', 'banner-marsh-state-fish-and-wildlife-area-il', null, 'IL', 40.478, -89.95);
-- INSERT INTO activities (park_id, name, description) VALUES (5, 'Boating', '');
-- INSERT INTO activities (park_id, name, description) VALUES (5, 'Dog Training', '');
-- INSERT INTO activities (park_id, name, description) VALUES (5, 'Fishing', '');
-- INSERT INTO activities (park_id, name, description) VALUES (5, 'Hunting', '');

-- -- Reset sequences to continue from 132
-- SELECT setval('parks_id_seq', 132, false);
-- SELECT setval('activities_id_seq', (SELECT MAX(id) FROM activities), true);

-- COMMIT;

-- -- Inserted 131 parks