-- Seed data from parks.json
-- Auto-generated by generate_seed.py
-- DO NOT EDIT THIS FILE MANUALLY - regenerate using: python3 database/generate_seed.py

BEGIN;

INSERT INTO parks (id, name, park_code, park_url, state_code, latitude, longitude) VALUES (1, 'Adeline Jay Geo-Karis Illinois Beach State Park', 'adeline-jay-geo-karis-illinois-beach', NULL, 'IL', 42.466, -87.81);
INSERT INTO activities (park_id, name, description) VALUES (1, 'Bike Trails', '');
INSERT INTO activities (park_id, name, description) VALUES (1, 'Camping', '');
INSERT INTO activities (park_id, name, description) VALUES (1, 'Cross Country Skiing', '');
INSERT INTO activities (park_id, name, description) VALUES (1, 'Fishing', '');
INSERT INTO activities (park_id, name, description) VALUES (1, 'Geocaching', '');
INSERT INTO activities (park_id, name, description) VALUES (1, 'Hiking Trails', '');
INSERT INTO activities (park_id, name, description) VALUES (1, 'SCUBA Diving', '');
INSERT INTO activities (park_id, name, description) VALUES (1, 'Swimming', '');

INSERT INTO parks (id, name, park_code, park_url, state_code, latitude, longitude) VALUES (2, 'Anderson Lake SFWA', 'anderson-lake-sfwa-il', null, 'IL', 40.19, -90.213);
INSERT INTO activities (park_id, name, description) VALUES (2, 'Boating', '');
INSERT INTO activities (park_id, name, description) VALUES (2, 'Camping', '');
INSERT INTO activities (park_id, name, description) VALUES (2, 'Fishing', '');
INSERT INTO activities (park_id, name, description) VALUES (2, 'Hunting', '');
INSERT INTO activities (park_id, name, description) VALUES (2, 'Picnicking', '');

INSERT INTO parks (id, name, park_code, park_url, state_code, latitude, longitude) VALUES (3, 'Apple River Canyon State Park', 'apple-river-canyon-state-park-il' , null, 'IL', 42.448, -90.043);
INSERT INTO activities (park_id, name, description) VALUES (3, 'Camping', '');
INSERT INTO activities (park_id, name, description) VALUES (3, 'Fishing', '');
INSERT INTO activities (park_id, name, description) VALUES (3, 'Hiking Trails', '');
INSERT INTO activities (park_id, name, description) VALUES (3, 'Hunting', '');
INSERT INTO activities (park_id, name, description) VALUES (3, 'Picnicking', '');

INSERT INTO parks (id, name, park_code, park_url, state_code, latitude, longitude) VALUES (4, 'Argyle Lake State Park', 'argyle-lake-state-park-il', null, 'IL', 40.449, -90.803);
INSERT INTO activities (park_id, name, description) VALUES (4, 'Archery Range', '');
INSERT INTO activities (park_id, name, description) VALUES (4, 'Boating', '');
INSERT INTO activities (park_id, name, description) VALUES (4, 'Camping', '');
INSERT INTO activities (park_id, name, description) VALUES (4, 'Equestrian Trails', '');
INSERT INTO activities (park_id, name, description) VALUES (4, 'Fishing', '');
INSERT INTO activities (park_id, name, description) VALUES (4, 'Hiking Trails', '');
INSERT INTO activities (park_id, name, description) VALUES (4, 'Hunting', '');
INSERT INTO activities (park_id, name, description) VALUES (4, 'Metal Detecting', '');
INSERT INTO activities (park_id, name, description) VALUES (4, 'Mountain Bike Trails', '');
INSERT INTO activities (park_id, name, description) VALUES (4, 'SCUBA Diving', '');
INSERT INTO activities (park_id, name, description) VALUES (4, 'Shelter Reservations', '');
INSERT INTO activities (park_id, name, description) VALUES (4, 'Snowmobile Trails', '');

INSERT INTO parks (id, name, park_code, park_url, state_code, latitude, longitude) VALUES (5, 'Banner Marsh State Fish and Wildlife Area', 'banner-marsh-state-fish-and-wildlife-area-il', null, 'IL', 40.478, -89.95);
INSERT INTO activities (park_id, name, description) VALUES (5, 'Boating', '');
INSERT INTO activities (park_id, name, description) VALUES (5, 'Dog Training', '');
INSERT INTO activities (park_id, name, description) VALUES (5, 'Fishing', '');
INSERT INTO activities (park_id, name, description) VALUES (5, 'Hunting', '');

-- INSERT INTO parks (id, name, state_code, latitude, longitude) VALUES (6, 'Beall Woods State Park', 'IL', 38.354, -87.828);
-- INSERT INTO activities (park_id, name, description) VALUES (6, 'Boating', '');
-- INSERT INTO activities (park_id, name, description) VALUES (6, 'Camping', '');
-- INSERT INTO activities (park_id, name, description) VALUES (6, 'Fishing', '');
-- INSERT INTO activities (park_id, name, description) VALUES (6, 'Hiking Trails', '');
-- INSERT INTO activities (park_id, name, description) VALUES (6, 'Metal Detecting', '');

-- INSERT INTO parks (id, name, state_code, latitude, longitude) VALUES (7, 'Beaver Dam State Park', 'IL', 39.209, -89.974);
-- INSERT INTO activities (park_id, name, description) VALUES (7, 'Archery Range', '');
-- INSERT INTO activities (park_id, name, description) VALUES (7, 'Boating', '');
-- INSERT INTO activities (park_id, name, description) VALUES (7, 'Camping', '');
-- INSERT INTO activities (park_id, name, description) VALUES (7, 'Cross Country Skiing', '');
-- INSERT INTO activities (park_id, name, description) VALUES (7, 'Fishing', '');
-- INSERT INTO activities (park_id, name, description) VALUES (7, 'Hiking Trails', '');
-- INSERT INTO activities (park_id, name, description) VALUES (7, 'Hunting', '');
-- INSERT INTO activities (park_id, name, description) VALUES (7, 'Shelter Reservations', '');

-- INSERT INTO parks (id, name, state_code, latitude, longitude) VALUES (8, 'Big Bend', 'IL', 41.64905, -90.0183);

-- INSERT INTO parks (id, name, state_code, latitude, longitude) VALUES (9, 'Big River State Forest', 'IL', 41.049, -90.93);
-- INSERT INTO activities (park_id, name, description) VALUES (9, 'Boating', '');
-- INSERT INTO activities (park_id, name, description) VALUES (9, 'Camping', '');
-- INSERT INTO activities (park_id, name, description) VALUES (9, 'Equestrian Trails', '');
-- INSERT INTO activities (park_id, name, description) VALUES (9, 'Fishing', '');
-- INSERT INTO activities (park_id, name, description) VALUES (9, 'Hiking Trails', '');
-- INSERT INTO activities (park_id, name, description) VALUES (9, 'Hunting', '');

-- INSERT INTO parks (id, name, state_code, latitude, longitude) VALUES (10, 'Buffalo Rock State Park', 'IL', 41.328, -88.91);
-- INSERT INTO activities (park_id, name, description) VALUES (10, 'Bike Trails', '');
-- INSERT INTO activities (park_id, name, description) VALUES (10, 'Cross Country Skiing', '');
-- INSERT INTO activities (park_id, name, description) VALUES (10, 'Geocaching', '');
-- INSERT INTO activities (park_id, name, description) VALUES (10, 'Hiking Trails', '');
-- INSERT INTO activities (park_id, name, description) VALUES (10, 'Hunting', '');
-- INSERT INTO activities (park_id, name, description) VALUES (10, 'Shelter Reservations', '');

-- INSERT INTO parks (id, name, state_code, latitude, longitude) VALUES (11, 'Burning Star State Fish and Wildlife Area', 'IL', 37.838, -89.182);
-- INSERT INTO activities (park_id, name, description) VALUES (11, 'Fishing', '');
-- INSERT INTO activities (park_id, name, description) VALUES (11, 'Hunting', '');

-- INSERT INTO parks (id, name, state_code, latitude, longitude) VALUES (12, 'Cache River State Natural Area', 'IL', 37.335, -88.938);
-- INSERT INTO activities (park_id, name, description) VALUES (12, 'Boating', '');
-- INSERT INTO activities (park_id, name, description) VALUES (12, 'Canoe Trails', '');
-- INSERT INTO activities (park_id, name, description) VALUES (12, 'Fishing', '');
-- INSERT INTO activities (park_id, name, description) VALUES (12, 'Hiking Trails', '');
-- INSERT INTO activities (park_id, name, description) VALUES (12, 'Hunting', '');

-- INSERT INTO parks (id, name, state_code, latitude, longitude) VALUES (13, 'Cape Bend State Fish and Wildlife Area', 'IL', 37.27762, -89.44931);

-- INSERT INTO parks (id, name, state_code, latitude, longitude) VALUES (14, 'Carlyle Lake SFWA', 'IL', 38.961, -89.094);
-- INSERT INTO activities (park_id, name, description) VALUES (14, 'Fishing', '');
-- INSERT INTO activities (park_id, name, description) VALUES (14, 'Hunting', '');

-- INSERT INTO parks (id, name, state_code, latitude, longitude) VALUES (15, 'Castle Rock State Park', 'IL', 41.978, -89.364);
-- INSERT INTO activities (park_id, name, description) VALUES (15, 'Boating', '');
-- INSERT INTO activities (park_id, name, description) VALUES (15, 'Camping', '');
-- INSERT INTO activities (park_id, name, description) VALUES (15, 'Canoeing', '');
-- INSERT INTO activities (park_id, name, description) VALUES (15, 'Cross Country Skiing', '');
-- INSERT INTO activities (park_id, name, description) VALUES (15, 'Fishing', '');
-- INSERT INTO activities (park_id, name, description) VALUES (15, 'Geocaching', '');
-- INSERT INTO activities (park_id, name, description) VALUES (15, 'Hiking Trails', '');
-- INSERT INTO activities (park_id, name, description) VALUES (15, 'Hunting', '');
-- INSERT INTO activities (park_id, name, description) VALUES (15, 'Metal Detecting', '');
-- INSERT INTO activities (park_id, name, description) VALUES (15, 'Shelter Reservations', '');

-- INSERT INTO parks (id, name, state_code, latitude, longitude) VALUES (16, 'Cave-in-Rock State Park', 'IL', 37.469, -88.159);
-- INSERT INTO activities (park_id, name, description) VALUES (16, 'Camping', '');
-- INSERT INTO activities (park_id, name, description) VALUES (16, 'Fishing', '');
-- INSERT INTO activities (park_id, name, description) VALUES (16, 'Geocaching', '');
-- INSERT INTO activities (park_id, name, description) VALUES (16, 'Hiking Trails', '');
-- INSERT INTO activities (park_id, name, description) VALUES (16, 'Metal Detecting', '');

-- INSERT INTO parks (id, name, state_code, latitude, longitude) VALUES (17, 'Chain O'' Lakes State Park', 'IL', 42.467, -88.189);
-- INSERT INTO activities (park_id, name, description) VALUES (17, 'Archery', '');
-- INSERT INTO activities (park_id, name, description) VALUES (17, 'Bike Trails', '');
-- INSERT INTO activities (park_id, name, description) VALUES (17, 'Boating', '');
-- INSERT INTO activities (park_id, name, description) VALUES (17, 'Camping', '');
-- INSERT INTO activities (park_id, name, description) VALUES (17, 'Concession/Boat Rental', '');
-- INSERT INTO activities (park_id, name, description) VALUES (17, 'Fishing', '');
-- INSERT INTO activities (park_id, name, description) VALUES (17, 'Hunting', '');
-- INSERT INTO activities (park_id, name, description) VALUES (17, 'Picnicking', '');
-- INSERT INTO activities (park_id, name, description) VALUES (17, 'Facilities for Visitors with Disabilities', '');
-- INSERT INTO activities (park_id, name, description) VALUES (17, 'Trails', '');
-- INSERT INTO activities (park_id, name, description) VALUES (17, 'Winter Sports', '');
-- INSERT INTO activities (park_id, name, description) VALUES (17, 'Trail Map', '');

-- INSERT INTO parks (id, name, state_code, latitude, longitude) VALUES (18, 'Channahon State Park', 'IL', 41.424, -88.228);
-- INSERT INTO activities (park_id, name, description) VALUES (18, 'Camping', '');
-- INSERT INTO activities (park_id, name, description) VALUES (18, 'Canoeing', '');
-- INSERT INTO activities (park_id, name, description) VALUES (18, 'Fishing', '');
-- INSERT INTO activities (park_id, name, description) VALUES (18, 'Picnicking', '');
-- INSERT INTO activities (park_id, name, description) VALUES (18, 'Trail Access', '');

-- INSERT INTO parks (id, name, state_code, latitude, longitude) VALUES (19, 'Clinton Lake State Recreation Area', 'IL', 40.161, -88.789);
-- INSERT INTO activities (park_id, name, description) VALUES (19, 'Archery Range', '');
-- INSERT INTO activities (park_id, name, description) VALUES (19, 'Boating', '');
-- INSERT INTO activities (park_id, name, description) VALUES (19, 'Camping', '');
-- INSERT INTO activities (park_id, name, description) VALUES (19, 'Concession', '');
-- INSERT INTO activities (park_id, name, description) VALUES (19, 'Cross Country Skiing', '');
-- INSERT INTO activities (park_id, name, description) VALUES (19, 'Dog Training', '');
-- INSERT INTO activities (park_id, name, description) VALUES (19, 'Equestrian Trails', '');
-- INSERT INTO activities (park_id, name, description) VALUES (19, 'Fishing', '');
-- INSERT INTO activities (park_id, name, description) VALUES (19, 'Hiking Trails', '');
-- INSERT INTO activities (park_id, name, description) VALUES (19, 'Hunting', '');
-- INSERT INTO activities (park_id, name, description) VALUES (19, 'Jet Skiing', '');
-- INSERT INTO activities (park_id, name, description) VALUES (19, 'SCUBA Diving', '');
-- INSERT INTO activities (park_id, name, description) VALUES (19, 'Shelter Reservations', '');
-- INSERT INTO activities (park_id, name, description) VALUES (19, 'Swimming', '');
-- INSERT INTO activities (park_id, name, description) VALUES (19, 'Water Skiing', '');

-- INSERT INTO parks (id, name, state_code, latitude, longitude) VALUES (20, 'Coffeen Lake State Fish and Wildlife Area', 'IL', 39.057, -89.414);
-- INSERT INTO activities (park_id, name, description) VALUES (20, 'Archery Range', '');
-- INSERT INTO activities (park_id, name, description) VALUES (20, 'Boating', '');
-- INSERT INTO activities (park_id, name, description) VALUES (20, 'Camping', '');
-- INSERT INTO activities (park_id, name, description) VALUES (20, 'Fishing', '');
-- INSERT INTO activities (park_id, name, description) VALUES (20, 'Hiking Trails', '');
-- INSERT INTO activities (park_id, name, description) VALUES (20, 'Hunting', '');
-- INSERT INTO activities (park_id, name, description) VALUES (20, 'Shelter Reservations', '');

-- INSERT INTO parks (id, name, state_code, latitude, longitude) VALUES (21, 'Crawford County Fish and Wildlife Area', 'IL', 39.09905, -87.70246);

-- INSERT INTO parks (id, name, state_code, latitude, longitude) VALUES (22, 'Delabar State Park', 'IL', 40.966, -90.938);
-- INSERT INTO activities (park_id, name, description) VALUES (22, 'Boating', '');
-- INSERT INTO activities (park_id, name, description) VALUES (22, 'Camping', '');
-- INSERT INTO activities (park_id, name, description) VALUES (22, 'Fishing', '');
-- INSERT INTO activities (park_id, name, description) VALUES (22, 'Hiking Trails', '');
-- INSERT INTO activities (park_id, name, description) VALUES (22, 'Picnicking', '');
-- INSERT INTO activities (park_id, name, description) VALUES (22, 'Playground', '');

-- INSERT INTO parks (id, name, state_code, latitude, longitude) VALUES (23, 'Des Plaines State Fish and Wildlife Area', 'IL', 41.372, -88.207);
-- INSERT INTO activities (park_id, name, description) VALUES (23, 'Archery Range', '');
-- INSERT INTO activities (park_id, name, description) VALUES (23, 'Boating', '');
-- INSERT INTO activities (park_id, name, description) VALUES (23, 'Camping', '');
-- INSERT INTO activities (park_id, name, description) VALUES (23, 'Dog Training', '');
-- INSERT INTO activities (park_id, name, description) VALUES (23, 'Equestrian Trails', '');
-- INSERT INTO activities (park_id, name, description) VALUES (23, 'Fishing', '');
-- INSERT INTO activities (park_id, name, description) VALUES (23, 'Geocaching', '');
-- INSERT INTO activities (park_id, name, description) VALUES (23, 'Hunting', '');
-- INSERT INTO activities (park_id, name, description) VALUES (23, 'Jet Skiing', '');
-- INSERT INTO activities (park_id, name, description) VALUES (23, 'Water Skiing', '');

-- INSERT INTO parks (id, name, state_code, latitude, longitude) VALUES (24, 'Devils Island Wildlife Management Area', 'IL', 37.32748, -89.43405);

-- INSERT INTO parks (id, name, state_code, latitude, longitude) VALUES (25, 'Dixon Springs State Park', 'IL', 37.381, -88.666);
-- INSERT INTO activities (park_id, name, description) VALUES (25, 'Camping', '');
-- INSERT INTO activities (park_id, name, description) VALUES (25, 'Fishing', '');
-- INSERT INTO activities (park_id, name, description) VALUES (25, 'Hiking Trails', '');
-- INSERT INTO activities (park_id, name, description) VALUES (25, 'Hunting', '');
-- INSERT INTO activities (park_id, name, description) VALUES (25, 'Swimming pool', '');

-- INSERT INTO parks (id, name, state_code, latitude, longitude) VALUES (26, 'Donnelley/DePue SFWAs', 'IL', 41.324, -89.308);
-- INSERT INTO activities (park_id, name, description) VALUES (26, 'Boating', '');
-- INSERT INTO activities (park_id, name, description) VALUES (26, 'Equestrian trails', '');
-- INSERT INTO activities (park_id, name, description) VALUES (26, 'Fishing', '');
-- INSERT INTO activities (park_id, name, description) VALUES (26, 'Hiking Trails', '');
-- INSERT INTO activities (park_id, name, description) VALUES (26, 'Hunting', '');

-- INSERT INTO parks (id, name, state_code, latitude, longitude) VALUES (27, 'Eagle Creek State Park', 'IL', 39.51, -88.719);
-- INSERT INTO activities (park_id, name, description) VALUES (27, 'Boating', '');
-- INSERT INTO activities (park_id, name, description) VALUES (27, 'Bow Range', '');
-- INSERT INTO activities (park_id, name, description) VALUES (27, 'Camping', '');
-- INSERT INTO activities (park_id, name, description) VALUES (27, 'Cross Country Skiing', '');
-- INSERT INTO activities (park_id, name, description) VALUES (27, 'Equestrian Trails', '');
-- INSERT INTO activities (park_id, name, description) VALUES (27, 'Fishing', '');
-- INSERT INTO activities (park_id, name, description) VALUES (27, 'Golfing', '');
-- INSERT INTO activities (park_id, name, description) VALUES (27, 'Hiking Trails', '');
-- INSERT INTO activities (park_id, name, description) VALUES (27, 'Hunting', '');
-- INSERT INTO activities (park_id, name, description) VALUES (27, 'Picnicking', '');
-- INSERT INTO activities (park_id, name, description) VALUES (27, 'Playground', '');
-- INSERT INTO activities (park_id, name, description) VALUES (27, 'Snowmobile Trails', '');
-- INSERT INTO activities (park_id, name, description) VALUES (27, 'Water Skiing', '');

-- INSERT INTO parks (id, name, state_code, latitude, longitude) VALUES (28, 'Edward R. Madigan State Park', 'IL', 40.117, -89.4);
-- INSERT INTO activities (park_id, name, description) VALUES (28, 'Boating', '');
-- INSERT INTO activities (park_id, name, description) VALUES (28, 'Cross Country Skiing', '');
-- INSERT INTO activities (park_id, name, description) VALUES (28, 'Dog Training', '');
-- INSERT INTO activities (park_id, name, description) VALUES (28, 'Fishing', '');
-- INSERT INTO activities (park_id, name, description) VALUES (28, 'Hiking Trails', '');
-- INSERT INTO activities (park_id, name, description) VALUES (28, 'Hunting', '');
-- INSERT INTO activities (park_id, name, description) VALUES (28, 'Shelter Reservations', '');

-- INSERT INTO parks (id, name, state_code, latitude, longitude) VALUES (29, 'Eldon Hazlet State Recreation Area', 'IL', 38.669, -89.324);
-- INSERT INTO activities (park_id, name, description) VALUES (29, 'Archery Range', '');
-- INSERT INTO activities (park_id, name, description) VALUES (29, 'Boating', '');
-- INSERT INTO activities (park_id, name, description) VALUES (29, 'Camping', '');
-- INSERT INTO activities (park_id, name, description) VALUES (29, 'Dog Training', '');
-- INSERT INTO activities (park_id, name, description) VALUES (29, 'Fishing', '');
-- INSERT INTO activities (park_id, name, description) VALUES (29, 'Geocaching', '');
-- INSERT INTO activities (park_id, name, description) VALUES (29, 'Hiking Trails', '');
-- INSERT INTO activities (park_id, name, description) VALUES (29, 'Hunting', '');
-- INSERT INTO activities (park_id, name, description) VALUES (29, 'Shelter Reservations', '');
-- INSERT INTO activities (park_id, name, description) VALUES (29, 'Swimming', '');

-- INSERT INTO parks (id, name, state_code, latitude, longitude) VALUES (30, 'Fall Creek Scenic Overlook SNA', 'IL', 39.785, -91.295);
-- INSERT INTO activities (park_id, name, description) VALUES (30, 'Fishing', '');
-- INSERT INTO activities (park_id, name, description) VALUES (30, 'Hiking Trails', '');
-- INSERT INTO activities (park_id, name, description) VALUES (30, 'Hunting', '');
-- INSERT INTO activities (park_id, name, description) VALUES (30, 'Metal Detecting', '');

-- INSERT INTO parks (id, name, state_code, latitude, longitude) VALUES (31, 'Ferne Clyffe State Park', 'IL', 37.531, -88.97);
-- INSERT INTO activities (park_id, name, description) VALUES (31, 'Camping', '');
-- INSERT INTO activities (park_id, name, description) VALUES (31, 'Equestrian Trails', '');
-- INSERT INTO activities (park_id, name, description) VALUES (31, 'Fishing', '');
-- INSERT INTO activities (park_id, name, description) VALUES (31, 'Hiking Trails', '');
-- INSERT INTO activities (park_id, name, description) VALUES (31, 'Hunting', '');
-- INSERT INTO activities (park_id, name, description) VALUES (31, 'Metal Detecting', '');
-- INSERT INTO activities (park_id, name, description) VALUES (31, 'Picnicking', '');
-- INSERT INTO activities (park_id, name, description) VALUES (31, 'Rock Climbing', '');
-- INSERT INTO activities (park_id, name, description) VALUES (31, 'Shelter Reservations', '');

-- INSERT INTO parks (id, name, state_code, latitude, longitude) VALUES (32, 'Fort Massac State Park', 'IL', 37.144, -88.712);
-- INSERT INTO activities (park_id, name, description) VALUES (32, 'Bike Trails', '');
-- INSERT INTO activities (park_id, name, description) VALUES (32, 'Boating', '');
-- INSERT INTO activities (park_id, name, description) VALUES (32, 'Camping', '');
-- INSERT INTO activities (park_id, name, description) VALUES (32, 'Fishing', '');
-- INSERT INTO activities (park_id, name, description) VALUES (32, 'Hiking Trails', '');
-- INSERT INTO activities (park_id, name, description) VALUES (32, 'Hunting', '');
-- INSERT INTO activities (park_id, name, description) VALUES (32, 'Shelter Reservations', '');
-- INSERT INTO activities (park_id, name, description) VALUES (32, 'Water Skiing', '');

-- INSERT INTO parks (id, name, state_code, latitude, longitude) VALUES (33, 'Fox Ridge State Park', 'IL', 39.404, -88.147);
-- INSERT INTO activities (park_id, name, description) VALUES (33, 'Picnicking', '');
-- INSERT INTO activities (park_id, name, description) VALUES (33, 'Camping', '');
-- INSERT INTO activities (park_id, name, description) VALUES (33, 'Trails', '');
-- INSERT INTO activities (park_id, name, description) VALUES (33, 'Fishing and Boating', '');
-- INSERT INTO activities (park_id, name, description) VALUES (33, 'Hunting', '');

-- INSERT INTO parks (id, name, state_code, latitude, longitude) VALUES (34, 'Frank Holten State Park', 'IL', 38.594, -90.105);
-- INSERT INTO activities (park_id, name, description) VALUES (34, 'Archery Range', '');
-- INSERT INTO activities (park_id, name, description) VALUES (34, 'Boating', '');
-- INSERT INTO activities (park_id, name, description) VALUES (34, 'Fishing', '');
-- INSERT INTO activities (park_id, name, description) VALUES (34, 'Geocaching', '');
-- INSERT INTO activities (park_id, name, description) VALUES (34, 'Golfing', '');
-- INSERT INTO activities (park_id, name, description) VALUES (34, 'Hunting', '');
-- INSERT INTO activities (park_id, name, description) VALUES (34, 'Metal Detecting', '');
-- INSERT INTO activities (park_id, name, description) VALUES (34, 'Shelter Reservations', '');

-- INSERT INTO parks (id, name, state_code, latitude, longitude) VALUES (35, 'Franklin Creek State Natural Area', 'IL', 41.857, -89.352);
-- INSERT INTO activities (park_id, name, description) VALUES (35, 'Archery Range', '');
-- INSERT INTO activities (park_id, name, description) VALUES (35, 'Cross Country Skiing', '');
-- INSERT INTO activities (park_id, name, description) VALUES (35, 'Equestrian Trails', '');
-- INSERT INTO activities (park_id, name, description) VALUES (35, 'Fishing', '');
-- INSERT INTO activities (park_id, name, description) VALUES (35, 'Hiking Trails', '');
-- INSERT INTO activities (park_id, name, description) VALUES (35, 'Hunting', '');
-- INSERT INTO activities (park_id, name, description) VALUES (35, 'Shelter Reservations', '');
-- INSERT INTO activities (park_id, name, description) VALUES (35, 'Snowmobile Trails', '');

-- INSERT INTO parks (id, name, state_code, latitude, longitude) VALUES (36, 'Fults Hill Prairie State Natural Area', 'IL', 38.157, -90.186);
-- INSERT INTO activities (park_id, name, description) VALUES (36, 'Hiking', '');
-- INSERT INTO activities (park_id, name, description) VALUES (36, 'Hunting', '');

-- INSERT INTO parks (id, name, state_code, latitude, longitude) VALUES (37, 'Gebhard Woods State Park', 'IL', 41.357, -88.436);
-- INSERT INTO activities (park_id, name, description) VALUES (37, 'Camping', '');
-- INSERT INTO activities (park_id, name, description) VALUES (37, 'Fishing', '');
-- INSERT INTO activities (park_id, name, description) VALUES (37, 'Hiking Trails', '');
-- INSERT INTO activities (park_id, name, description) VALUES (37, 'Shelter Reservations', '');

-- INSERT INTO parks (id, name, state_code, latitude, longitude) VALUES (38, 'Giant City State Park', 'IL', 37.602, -89.189);
-- INSERT INTO activities (park_id, name, description) VALUES (38, 'Activities', '');

-- INSERT INTO parks (id, name, state_code, latitude, longitude) VALUES (39, 'Golconda Marina', 'IL', 37.372, -88.482);
-- INSERT INTO activities (park_id, name, description) VALUES (39, 'Boating', '');
-- INSERT INTO activities (park_id, name, description) VALUES (39, 'Fishing', '');

-- INSERT INTO parks (id, name, state_code, latitude, longitude) VALUES (40, 'Goose Lake Prairie State Natural Area', 'IL', 41.381, -89.691);
-- INSERT INTO activities (park_id, name, description) VALUES (40, 'Cross Country Skiing', '');
-- INSERT INTO activities (park_id, name, description) VALUES (40, 'Hiking Trails', '');
-- INSERT INTO activities (park_id, name, description) VALUES (40, 'Hunting', '');
-- INSERT INTO activities (park_id, name, description) VALUES (40, 'Shelter Reservations', '');

-- INSERT INTO parks (id, name, state_code, latitude, longitude) VALUES (41, 'Green River SWA', 'IL', 41.635, -89.507);
-- INSERT INTO activities (park_id, name, description) VALUES (41, 'Camping', '');
-- INSERT INTO activities (park_id, name, description) VALUES (41, 'Equestrian Trails', '');
-- INSERT INTO activities (park_id, name, description) VALUES (41, 'Hiking Trails', '');
-- INSERT INTO activities (park_id, name, description) VALUES (41, 'Hunting', '');

-- INSERT INTO parks (id, name, state_code, latitude, longitude) VALUES (42, 'Hamilton County', 'IL', 38.058, -88.397);
-- INSERT INTO activities (park_id, name, description) VALUES (42, 'Boating', '');
-- INSERT INTO activities (park_id, name, description) VALUES (42, 'Camping', '');
-- INSERT INTO activities (park_id, name, description) VALUES (42, 'Equestrian Trails', '');
-- INSERT INTO activities (park_id, name, description) VALUES (42, 'Fishing', '');
-- INSERT INTO activities (park_id, name, description) VALUES (42, 'Hiking Trails', '');
-- INSERT INTO activities (park_id, name, description) VALUES (42, 'Hunting-Hand Trap', '');
-- INSERT INTO activities (park_id, name, description) VALUES (42, 'Picnicking', '');
-- INSERT INTO activities (park_id, name, description) VALUES (42, 'Playground', '');

-- INSERT INTO parks (id, name, state_code, latitude, longitude) VALUES (43, 'Harry ''Babe'' Woodyard State Natural Area', 'IL', 39.955986, -87.54872);

-- INSERT INTO parks (id, name, state_code, latitude, longitude) VALUES (44, 'Heidecke Lake SFWA', 'IL', 41.36, -88.325);
-- INSERT INTO activities (park_id, name, description) VALUES (44, 'Boating', '');
-- INSERT INTO activities (park_id, name, description) VALUES (44, 'Camping', '');
-- INSERT INTO activities (park_id, name, description) VALUES (44, 'Cross Country Skiing', '');
-- INSERT INTO activities (park_id, name, description) VALUES (44, 'Hiking Trails', '');
-- INSERT INTO activities (park_id, name, description) VALUES (44, 'Hunting', '');
-- INSERT INTO activities (park_id, name, description) VALUES (44, 'Tours', '');

-- INSERT INTO parks (id, name, state_code, latitude, longitude) VALUES (45, 'Henderson County Conservation Area', 'IL', 41.09, -90.936);
-- INSERT INTO activities (park_id, name, description) VALUES (45, 'Boating', '');
-- INSERT INTO activities (park_id, name, description) VALUES (45, 'Camping', '');
-- INSERT INTO activities (park_id, name, description) VALUES (45, 'Fishing', '');
-- INSERT INTO activities (park_id, name, description) VALUES (45, 'Picnicking', '');

-- INSERT INTO parks (id, name, state_code, latitude, longitude) VALUES (46, 'Hennepin Canal State Trail', 'IL', 41.381, -89.691);
-- INSERT INTO activities (park_id, name, description) VALUES (46, 'Bike Trails', '');
-- INSERT INTO activities (park_id, name, description) VALUES (46, 'Boating', '');
-- INSERT INTO activities (park_id, name, description) VALUES (46, 'Camping', '');
-- INSERT INTO activities (park_id, name, description) VALUES (46, 'Canoeing', '');
-- INSERT INTO activities (park_id, name, description) VALUES (46, 'Cross Country Skiing', '');
-- INSERT INTO activities (park_id, name, description) VALUES (46, 'Equestrian Trails', '');
-- INSERT INTO activities (park_id, name, description) VALUES (46, 'Fishing', '');
-- INSERT INTO activities (park_id, name, description) VALUES (46, 'Hiking Trails', '');
-- INSERT INTO activities (park_id, name, description) VALUES (46, 'Hunting', '');
-- INSERT INTO activities (park_id, name, description) VALUES (46, 'Shelter Reservations', '');
-- INSERT INTO activities (park_id, name, description) VALUES (46, 'Snowmobile Trails', '');

-- INSERT INTO parks (id, name, state_code, latitude, longitude) VALUES (47, 'Hidden Springs State Forest', 'IL', 39.315, -88.693);
-- INSERT INTO activities (park_id, name, description) VALUES (47, 'Camping', '');
-- INSERT INTO activities (park_id, name, description) VALUES (47, 'Fishing', '');
-- INSERT INTO activities (park_id, name, description) VALUES (47, 'Hiking Trails', '');
-- INSERT INTO activities (park_id, name, description) VALUES (47, 'Hunting', '');
-- INSERT INTO activities (park_id, name, description) VALUES (47, 'Picnicking', '');

-- INSERT INTO parks (id, name, state_code, latitude, longitude) VALUES (48, 'Horseshoe Lake Alexander County', 'IL', 37.14, -89.343);
-- INSERT INTO activities (park_id, name, description) VALUES (48, 'Boating', '');
-- INSERT INTO activities (park_id, name, description) VALUES (48, 'Fishing', '');
-- INSERT INTO activities (park_id, name, description) VALUES (48, 'Hunting', '');

-- INSERT INTO parks (id, name, state_code, latitude, longitude) VALUES (49, 'Horseshoe Lake State Park (Madison County)', 'IL', 38.703, -90.071);
-- INSERT INTO activities (park_id, name, description) VALUES (49, 'Boating', '');
-- INSERT INTO activities (park_id, name, description) VALUES (49, 'Camping', '');
-- INSERT INTO activities (park_id, name, description) VALUES (49, 'Dog Training', '');
-- INSERT INTO activities (park_id, name, description) VALUES (49, 'Fishing', '');
-- INSERT INTO activities (park_id, name, description) VALUES (49, 'Geocaching', '');
-- INSERT INTO activities (park_id, name, description) VALUES (49, 'Hiking Trails', '');
-- INSERT INTO activities (park_id, name, description) VALUES (49, 'Hunting', '');
-- INSERT INTO activities (park_id, name, description) VALUES (49, 'Metal Detecting', '');
-- INSERT INTO activities (park_id, name, description) VALUES (49, 'Picnicking', '');

-- INSERT INTO parks (id, name, state_code, latitude, longitude) VALUES (50, 'Illini State Park', 'IL', 41.321, -88.708);
-- INSERT INTO activities (park_id, name, description) VALUES (50, 'Boating', '');
-- INSERT INTO activities (park_id, name, description) VALUES (50, 'Camping', '');
-- INSERT INTO activities (park_id, name, description) VALUES (50, 'Cross Country Skiing', '');
-- INSERT INTO activities (park_id, name, description) VALUES (50, 'Fishing', '');
-- INSERT INTO activities (park_id, name, description) VALUES (50, 'Geocaching', '');
-- INSERT INTO activities (park_id, name, description) VALUES (50, 'Hiking Trails', '');
-- INSERT INTO activities (park_id, name, description) VALUES (50, 'Metal Detecting', '');
-- INSERT INTO activities (park_id, name, description) VALUES (50, 'Shelter Reservations', '');

-- INSERT INTO parks (id, name, state_code, latitude, longitude) VALUES (51, 'Illinois Caverns State Natural Area', 'IL', 38.234, -90.137);

-- INSERT INTO parks (id, name, state_code, latitude, longitude) VALUES (52, 'Illinois and Michigan Canal State Trail', 'IL', 41.39, -88.48);

-- INSERT INTO parks (id, name, state_code, latitude, longitude) VALUES (53, 'Iroquois County State Wildlife Area', 'IL', 40.994, -87.599);
-- INSERT INTO activities (park_id, name, description) VALUES (53, 'Archery Range', '');
-- INSERT INTO activities (park_id, name, description) VALUES (53, 'Dog Training', '');
-- INSERT INTO activities (park_id, name, description) VALUES (53, 'Hiking Trails', '');
-- INSERT INTO activities (park_id, name, description) VALUES (53, 'Hunting', '');
-- INSERT INTO activities (park_id, name, description) VALUES (53, 'Snowmobile Trails', '');

-- INSERT INTO parks (id, name, state_code, latitude, longitude) VALUES (54, 'James "Pate" Philip State Park', 'IL', 41.978, -88.257);
-- INSERT INTO activities (park_id, name, description) VALUES (54, 'Bike Trails', '');
-- INSERT INTO activities (park_id, name, description) VALUES (54, 'Cross Country Skiing', '');
-- INSERT INTO activities (park_id, name, description) VALUES (54, 'Fishing', '');
-- INSERT INTO activities (park_id, name, description) VALUES (54, 'Hiking Trails', '');
-- INSERT INTO activities (park_id, name, description) VALUES (54, 'Hunting', '');
-- INSERT INTO activities (park_id, name, description) VALUES (54, 'Shelter Reservations', '');

-- INSERT INTO parks (id, name, state_code, latitude, longitude) VALUES (55, 'Jim Edgar Panther Creek State Fish and Wildlife Area', 'IL', 39.998, -90.069);
-- INSERT INTO activities (park_id, name, description) VALUES (55, 'Archery Range', '');
-- INSERT INTO activities (park_id, name, description) VALUES (55, 'Bike Trails', '');
-- INSERT INTO activities (park_id, name, description) VALUES (55, 'Boating', '');
-- INSERT INTO activities (park_id, name, description) VALUES (55, 'Camping', '');
-- INSERT INTO activities (park_id, name, description) VALUES (55, 'Cross Country Skiing', '');
-- INSERT INTO activities (park_id, name, description) VALUES (55, 'Dog Training', '');
-- INSERT INTO activities (park_id, name, description) VALUES (55, 'Equestrian Trails', '');
-- INSERT INTO activities (park_id, name, description) VALUES (55, 'Fishing', '');
-- INSERT INTO activities (park_id, name, description) VALUES (55, 'Hunting', '');
-- INSERT INTO activities (park_id, name, description) VALUES (55, 'Metal Detecting', '');
-- INSERT INTO activities (park_id, name, description) VALUES (55, 'Mountain Bike Trails', '');
-- INSERT INTO activities (park_id, name, description) VALUES (55, 'Shelter Reservations', '');
-- INSERT INTO activities (park_id, name, description) VALUES (55, 'Snowmobile Trails', '');

-- INSERT INTO parks (id, name, state_code, latitude, longitude) VALUES (56, 'Johnson-Sauk Trail State Recreation Area', 'IL', 41.326, -89.892);
-- INSERT INTO activities (park_id, name, description) VALUES (56, 'Archery Range', '');
-- INSERT INTO activities (park_id, name, description) VALUES (56, 'Boating', '');
-- INSERT INTO activities (park_id, name, description) VALUES (56, 'Camping', '');
-- INSERT INTO activities (park_id, name, description) VALUES (56, 'Cross Country Skiing', '');
-- INSERT INTO activities (park_id, name, description) VALUES (56, 'Fishing', '');
-- INSERT INTO activities (park_id, name, description) VALUES (56, 'Geocaching', '');
-- INSERT INTO activities (park_id, name, description) VALUES (56, 'Hiking Trails', '');
-- INSERT INTO activities (park_id, name, description) VALUES (56, 'Hunting', '');
-- INSERT INTO activities (park_id, name, description) VALUES (56, 'Metal Detecting', '');
-- INSERT INTO activities (park_id, name, description) VALUES (56, 'Picnicking', '');

-- INSERT INTO parks (id, name, state_code, latitude, longitude) VALUES (57, 'Jubilee College State Park', 'IL', 40.824, -89.799);
-- INSERT INTO activities (park_id, name, description) VALUES (57, 'Camping', '');
-- INSERT INTO activities (park_id, name, description) VALUES (57, 'Cross Country Skiing', '');
-- INSERT INTO activities (park_id, name, description) VALUES (57, 'Equestrian Trails', '');
-- INSERT INTO activities (park_id, name, description) VALUES (57, 'Fishing', '');
-- INSERT INTO activities (park_id, name, description) VALUES (57, 'Geocaching', '');
-- INSERT INTO activities (park_id, name, description) VALUES (57, 'Hiking Trails', '');
-- INSERT INTO activities (park_id, name, description) VALUES (57, 'Hunting', '');
-- INSERT INTO activities (park_id, name, description) VALUES (57, 'Metal Detecting', '');
-- INSERT INTO activities (park_id, name, description) VALUES (57, 'Mountain Bike Trails', '');
-- INSERT INTO activities (park_id, name, description) VALUES (57, 'Picnicking', '');
-- INSERT INTO activities (park_id, name, description) VALUES (57, 'Snowmobile Trails', '');

-- INSERT INTO parks (id, name, state_code, latitude, longitude) VALUES (58, 'Kankakee River State Park', 'IL', 41.203, -87.979);
-- INSERT INTO activities (park_id, name, description) VALUES (58, 'Archery Range', '');
-- INSERT INTO activities (park_id, name, description) VALUES (58, 'Bike Trails', '');
-- INSERT INTO activities (park_id, name, description) VALUES (58, 'Boating', '');
-- INSERT INTO activities (park_id, name, description) VALUES (58, 'Camping', '');
-- INSERT INTO activities (park_id, name, description) VALUES (58, 'Canoeing', '');
-- INSERT INTO activities (park_id, name, description) VALUES (58, 'Cross Country Skiing', '');
-- INSERT INTO activities (park_id, name, description) VALUES (58, 'Dog Training', '');
-- INSERT INTO activities (park_id, name, description) VALUES (58, 'Equestrian Trails', '');
-- INSERT INTO activities (park_id, name, description) VALUES (58, 'Fishing', '');
-- INSERT INTO activities (park_id, name, description) VALUES (58, 'Geocaching', '');
-- INSERT INTO activities (park_id, name, description) VALUES (58, 'Hiking Trails', '');
-- INSERT INTO activities (park_id, name, description) VALUES (58, 'Hunting', '');
-- INSERT INTO activities (park_id, name, description) VALUES (58, 'Metal Detecting', '');
-- INSERT INTO activities (park_id, name, description) VALUES (58, 'Shelter Reservations', '');
-- INSERT INTO activities (park_id, name, description) VALUES (58, 'Snowmobile Trails', '');

-- INSERT INTO parks (id, name, state_code, latitude, longitude) VALUES (59, 'Kaskaskia River', 'IL', 39.582, -88.443);
-- INSERT INTO activities (park_id, name, description) VALUES (59, 'Boating', '');
-- INSERT INTO activities (park_id, name, description) VALUES (59, 'Camping', '');
-- INSERT INTO activities (park_id, name, description) VALUES (59, 'Fishing', '');
-- INSERT INTO activities (park_id, name, description) VALUES (59, 'Hiking Trails', '');
-- INSERT INTO activities (park_id, name, description) VALUES (59, 'Hunting', '');
-- INSERT INTO activities (park_id, name, description) VALUES (59, 'Picnicking', '');

-- INSERT INTO parks (id, name, state_code, latitude, longitude) VALUES (60, 'Kickapoo State Recreation Area', 'IL', 40.14, -87.735);
-- INSERT INTO activities (park_id, name, description) VALUES (60, 'Boating', '');
-- INSERT INTO activities (park_id, name, description) VALUES (60, 'Camping', '');
-- INSERT INTO activities (park_id, name, description) VALUES (60, 'Canoeing', '');
-- INSERT INTO activities (park_id, name, description) VALUES (60, 'Dog Training', '');
-- INSERT INTO activities (park_id, name, description) VALUES (60, 'Equestrian Trails', '');
-- INSERT INTO activities (park_id, name, description) VALUES (60, 'Fishing', '');
-- INSERT INTO activities (park_id, name, description) VALUES (60, 'Hiking Trails', '');
-- INSERT INTO activities (park_id, name, description) VALUES (60, 'Hunting', '');
-- INSERT INTO activities (park_id, name, description) VALUES (60, 'Mountain Bike Trails', '');
-- INSERT INTO activities (park_id, name, description) VALUES (60, 'SCUBA Diving', '');
-- INSERT INTO activities (park_id, name, description) VALUES (60, 'Shelter Reservations', '');

-- INSERT INTO parks (id, name, state_code, latitude, longitude) VALUES (61, 'Kidd Lake State Natural Area', 'IL', 38.14567, -90.2047);

-- INSERT INTO parks (id, name, state_code, latitude, longitude) VALUES (62, 'Kinkaid Lake SFWA', 'IL', 37.776, -89.379);
-- INSERT INTO activities (park_id, name, description) VALUES (62, 'Boating', '');
-- INSERT INTO activities (park_id, name, description) VALUES (62, 'Camping', '');
-- INSERT INTO activities (park_id, name, description) VALUES (62, 'Fishing', '');
-- INSERT INTO activities (park_id, name, description) VALUES (62, 'Hunting', '');
-- INSERT INTO activities (park_id, name, description) VALUES (62, 'Picnicking', '');
-- INSERT INTO activities (park_id, name, description) VALUES (62, 'Playground', '');

-- INSERT INTO parks (id, name, state_code, latitude, longitude) VALUES (63, 'LaSalle Lake SFWA', 'IL', 41.321, -88.711);
-- INSERT INTO activities (park_id, name, description) VALUES (63, 'Boating', '');
-- INSERT INTO activities (park_id, name, description) VALUES (63, 'Fishing', '');

-- INSERT INTO parks (id, name, state_code, latitude, longitude) VALUES (64, 'Lake Le-Aqua-Na State Recreation Area', 'IL', 42.423, -89.824);
-- INSERT INTO activities (park_id, name, description) VALUES (64, 'Bike Trails', '');
-- INSERT INTO activities (park_id, name, description) VALUES (64, 'Boating', '');
-- INSERT INTO activities (park_id, name, description) VALUES (64, 'Camping', '');
-- INSERT INTO activities (park_id, name, description) VALUES (64, 'Cross Country Skiing', '');
-- INSERT INTO activities (park_id, name, description) VALUES (64, 'Equestrian Trails', '');
-- INSERT INTO activities (park_id, name, description) VALUES (64, 'Fishing', '');
-- INSERT INTO activities (park_id, name, description) VALUES (64, 'Geocaching', '');
-- INSERT INTO activities (park_id, name, description) VALUES (64, 'Hiking Trails', '');
-- INSERT INTO activities (park_id, name, description) VALUES (64, 'Hunting', '');
-- INSERT INTO activities (park_id, name, description) VALUES (64, 'Metal Detecting', '');
-- INSERT INTO activities (park_id, name, description) VALUES (64, 'Mountain Bike Trails', '');
-- INSERT INTO activities (park_id, name, description) VALUES (64, 'Picnicking', '');
-- INSERT INTO activities (park_id, name, description) VALUES (64, 'Swimming', '');

-- INSERT INTO parks (id, name, state_code, latitude, longitude) VALUES (65, 'Lake Murphysboro State Park', 'IL', 37.773, -89.379);
-- INSERT INTO activities (park_id, name, description) VALUES (65, 'Archery', '');
-- INSERT INTO activities (park_id, name, description) VALUES (65, 'boating', '');
-- INSERT INTO activities (park_id, name, description) VALUES (65, 'Camping', '');
-- INSERT INTO activities (park_id, name, description) VALUES (65, 'Fishing', '');
-- INSERT INTO activities (park_id, name, description) VALUES (65, 'Hiking Trails', '');
-- INSERT INTO activities (park_id, name, description) VALUES (65, 'Picnicking', '');
-- INSERT INTO activities (park_id, name, description) VALUES (65, 'Accessibility', '');

-- INSERT INTO parks (id, name, state_code, latitude, longitude) VALUES (66, 'Lincoln Trail State Park', 'IL', 39.347, -87.704);
-- INSERT INTO activities (park_id, name, description) VALUES (66, 'Boating', '');
-- INSERT INTO activities (park_id, name, description) VALUES (66, 'Camping', '');
-- INSERT INTO activities (park_id, name, description) VALUES (66, 'Fishing', '');
-- INSERT INTO activities (park_id, name, description) VALUES (66, 'Hiking Trails', '');
-- INSERT INTO activities (park_id, name, description) VALUES (66, 'Hunting', '');

-- INSERT INTO parks (id, name, state_code, latitude, longitude) VALUES (67, 'Lincoln Trail Homestead State Park & Memorial', 'IL', 39.803, -89.102);
-- INSERT INTO activities (park_id, name, description) VALUES (67, 'Boating', '');
-- INSERT INTO activities (park_id, name, description) VALUES (67, 'Fishing', '');
-- INSERT INTO activities (park_id, name, description) VALUES (67, 'Hiking Trails', '');
-- INSERT INTO activities (park_id, name, description) VALUES (67, 'Picnicking', '');
-- INSERT INTO activities (park_id, name, description) VALUES (67, 'Facebook Page', '');

-- INSERT INTO parks (id, name, state_code, latitude, longitude) VALUES (68, 'Little Grassy Fish Hatchery', 'IL', 37.651, -89.149);
-- INSERT INTO activities (park_id, name, description) VALUES (68, 'Tours', '');

-- INSERT INTO parks (id, name, state_code, latitude, longitude) VALUES (69, 'Lowden State Park', 'IL', 42.035, -89.325);
-- INSERT INTO activities (park_id, name, description) VALUES (69, 'Boating', '');
-- INSERT INTO activities (park_id, name, description) VALUES (69, 'Camping', '');
-- INSERT INTO activities (park_id, name, description) VALUES (69, 'Canoeing', '');
-- INSERT INTO activities (park_id, name, description) VALUES (69, 'Cross Country Skiing', '');
-- INSERT INTO activities (park_id, name, description) VALUES (69, 'Fishing', '');
-- INSERT INTO activities (park_id, name, description) VALUES (69, 'Hiking Trails', '');
-- INSERT INTO activities (park_id, name, description) VALUES (69, 'Hunting', '');
-- INSERT INTO activities (park_id, name, description) VALUES (69, 'Metal Detecting', '');

-- INSERT INTO parks (id, name, state_code, latitude, longitude) VALUES (70, 'Lowden-Miller', 'IL', 41.962, -89.366);
-- INSERT INTO activities (park_id, name, description) VALUES (70, 'Cross Country Skiing', '');
-- INSERT INTO activities (park_id, name, description) VALUES (70, 'Equestrian Trails', '');
-- INSERT INTO activities (park_id, name, description) VALUES (70, 'Hiking Trails', '');

-- INSERT INTO parks (id, name, state_code, latitude, longitude) VALUES (71, 'Mackinaw River SFWA', 'IL', 40.554, -89.292);
-- INSERT INTO activities (park_id, name, description) VALUES (71, 'Canoeing', '');
-- INSERT INTO activities (park_id, name, description) VALUES (71, 'Fishing', '');
-- INSERT INTO activities (park_id, name, description) VALUES (71, 'Hiking Trails', '');
-- INSERT INTO activities (park_id, name, description) VALUES (71, 'Hunting', '');

-- INSERT INTO parks (id, name, state_code, latitude, longitude) VALUES (72, 'Marseilles State Fish & Wildlife Area (Upland Game/Furbearer)', 'IL', 41.27725, -88.68498);

-- INSERT INTO parks (id, name, state_code, latitude, longitude) VALUES (73, 'Marshall SFWA', 'IL', 40.955, -89.429);
-- INSERT INTO activities (park_id, name, description) VALUES (73, 'Boating', '');
-- INSERT INTO activities (park_id, name, description) VALUES (73, 'Camping', '');
-- INSERT INTO activities (park_id, name, description) VALUES (73, 'Canoeing', '');
-- INSERT INTO activities (park_id, name, description) VALUES (73, 'Cross Country Skiing', '');
-- INSERT INTO activities (park_id, name, description) VALUES (73, 'Fishing', '');
-- INSERT INTO activities (park_id, name, description) VALUES (73, 'Hiking trails', '');
-- INSERT INTO activities (park_id, name, description) VALUES (73, 'Hunting', '');
-- INSERT INTO activities (park_id, name, description) VALUES (73, 'Picnicking', '');

-- INSERT INTO parks (id, name, state_code, latitude, longitude) VALUES (74, 'Matthiessen State Park', 'IL', 41.286, -89.025);
-- INSERT INTO activities (park_id, name, description) VALUES (74, 'Archery Range', '');
-- INSERT INTO activities (park_id, name, description) VALUES (74, 'Camping', '');
-- INSERT INTO activities (park_id, name, description) VALUES (74, 'Cross Country Skiing', '');
-- INSERT INTO activities (park_id, name, description) VALUES (74, 'Equestrian Trails', '');
-- INSERT INTO activities (park_id, name, description) VALUES (74, 'Fishing', '');
-- INSERT INTO activities (park_id, name, description) VALUES (74, 'Geocaching', '');
-- INSERT INTO activities (park_id, name, description) VALUES (74, 'Hiking Trails', '');
-- INSERT INTO activities (park_id, name, description) VALUES (74, 'Hunting', '');
-- INSERT INTO activities (park_id, name, description) VALUES (74, 'Mountain Bike Trails', '');

-- INSERT INTO parks (id, name, state_code, latitude, longitude) VALUES (75, 'Mautino State Fish & Wildlife Area', 'IL', 41.323, -89.719);

-- INSERT INTO parks (id, name, state_code, latitude, longitude) VALUES (76, 'Mazonia-Braidwood State Fish and Wildlife Area', 'IL', 41.215, -88.27);
-- INSERT INTO activities (park_id, name, description) VALUES (76, 'Boating', '');
-- INSERT INTO activities (park_id, name, description) VALUES (76, 'Fishing', '');
-- INSERT INTO activities (park_id, name, description) VALUES (76, 'Hunting', '');

-- INSERT INTO parks (id, name, state_code, latitude, longitude) VALUES (77, 'Mermet Lake State Fish and Wildlife Area', 'IL', 37.275, -88.849);
-- INSERT INTO activities (park_id, name, description) VALUES (77, 'Archery Range', '');
-- INSERT INTO activities (park_id, name, description) VALUES (77, 'Boating', '');
-- INSERT INTO activities (park_id, name, description) VALUES (77, 'Fishing', '');
-- INSERT INTO activities (park_id, name, description) VALUES (77, 'Hiking Trails', '');
-- INSERT INTO activities (park_id, name, description) VALUES (77, 'Hunting', '');

-- INSERT INTO parks (id, name, state_code, latitude, longitude) VALUES (78, 'Middle Fork State Fish and Wildlife Area', 'IL', 40.193, -87.753);
-- INSERT INTO activities (park_id, name, description) VALUES (78, 'Boating', '');
-- INSERT INTO activities (park_id, name, description) VALUES (78, 'Camping', '');
-- INSERT INTO activities (park_id, name, description) VALUES (78, 'Canoeing', '');
-- INSERT INTO activities (park_id, name, description) VALUES (78, 'Cross Country Skiing', '');
-- INSERT INTO activities (park_id, name, description) VALUES (78, 'Dog Training', '');
-- INSERT INTO activities (park_id, name, description) VALUES (78, 'Equestrian Trails', '');
-- INSERT INTO activities (park_id, name, description) VALUES (78, 'Fishing', '');
-- INSERT INTO activities (park_id, name, description) VALUES (78, 'Hiking Trails', '');
-- INSERT INTO activities (park_id, name, description) VALUES (78, 'Hunting', '');
-- INSERT INTO activities (park_id, name, description) VALUES (78, 'Picnicking', '');

-- INSERT INTO parks (id, name, state_code, latitude, longitude) VALUES (79, 'Mississippi Palisades State Park', 'IL', 42.144, -90.168);
-- INSERT INTO activities (park_id, name, description) VALUES (79, 'Camping', '');
-- INSERT INTO activities (park_id, name, description) VALUES (79, 'Cross Country Skiing', '');
-- INSERT INTO activities (park_id, name, description) VALUES (79, 'Fishing', '');
-- INSERT INTO activities (park_id, name, description) VALUES (79, 'Geocaching', '');
-- INSERT INTO activities (park_id, name, description) VALUES (79, 'Hiking Trails', '');
-- INSERT INTO activities (park_id, name, description) VALUES (79, 'Hunting', '');
-- INSERT INTO activities (park_id, name, description) VALUES (79, 'Metal Detecting', '');
-- INSERT INTO activities (park_id, name, description) VALUES (79, 'Rock Climbing', '');
-- INSERT INTO activities (park_id, name, description) VALUES (79, 'Picnicking', '');

-- INSERT INTO parks (id, name, state_code, latitude, longitude) VALUES (80, 'Mississippi River SFWA', 'IL', 38.972, -90.471);
-- INSERT INTO activities (park_id, name, description) VALUES (80, 'Boating', '');
-- INSERT INTO activities (park_id, name, description) VALUES (80, 'Canoeing', '');
-- INSERT INTO activities (park_id, name, description) VALUES (80, 'Fishing', '');
-- INSERT INTO activities (park_id, name, description) VALUES (80, 'Hunting', '');
-- INSERT INTO activities (park_id, name, description) VALUES (80, 'Picnicking', '');

-- INSERT INTO parks (id, name, state_code, latitude, longitude) VALUES (81, 'Moraine Hills State Park & McHenry Dam State Park', 'IL', 42.323, -88.227);
-- INSERT INTO activities (park_id, name, description) VALUES (81, 'Bike Trails', '');
-- INSERT INTO activities (park_id, name, description) VALUES (81, 'Boating', '');
-- INSERT INTO activities (park_id, name, description) VALUES (81, 'Cross Country Skiing', '');
-- INSERT INTO activities (park_id, name, description) VALUES (81, 'Fishing', '');
-- INSERT INTO activities (park_id, name, description) VALUES (81, 'Geocaching', '');
-- INSERT INTO activities (park_id, name, description) VALUES (81, 'Hiking Trails', '');
-- INSERT INTO activities (park_id, name, description) VALUES (81, 'Hunting', '');
-- INSERT INTO activities (park_id, name, description) VALUES (81, 'Metal Detecting', '');
-- INSERT INTO activities (park_id, name, description) VALUES (81, 'Shelter Reservations', '');

-- INSERT INTO parks (id, name, state_code, latitude, longitude) VALUES (82, 'Moraine View State Park', 'IL', 40.415, -88.729);
-- INSERT INTO activities (park_id, name, description) VALUES (82, 'Archery Range', '');
-- INSERT INTO activities (park_id, name, description) VALUES (82, 'Boating', '');
-- INSERT INTO activities (park_id, name, description) VALUES (82, 'Camping', '');
-- INSERT INTO activities (park_id, name, description) VALUES (82, 'Cross Country Skiing', '');
-- INSERT INTO activities (park_id, name, description) VALUES (82, 'Equestrian Trails', '');
-- INSERT INTO activities (park_id, name, description) VALUES (82, 'Fishing', '');
-- INSERT INTO activities (park_id, name, description) VALUES (82, 'Hiking Trails', '');
-- INSERT INTO activities (park_id, name, description) VALUES (82, 'Hunting', '');
-- INSERT INTO activities (park_id, name, description) VALUES (82, 'Shelter Reservations', '');
-- INSERT INTO activities (park_id, name, description) VALUES (82, 'Swimming', '');

-- INSERT INTO parks (id, name, state_code, latitude, longitude) VALUES (83, 'Morrison-Rockwood State Park', 'IL', 41.848, -89.965);
-- INSERT INTO activities (park_id, name, description) VALUES (83, 'Archery Range', '');
-- INSERT INTO activities (park_id, name, description) VALUES (83, 'Boating', '');
-- INSERT INTO activities (park_id, name, description) VALUES (83, 'Camping', '');
-- INSERT INTO activities (park_id, name, description) VALUES (83, 'Cross Country Skiing', '');
-- INSERT INTO activities (park_id, name, description) VALUES (83, 'Equestrian Trails', '');
-- INSERT INTO activities (park_id, name, description) VALUES (83, 'Fishing', '');
-- INSERT INTO activities (park_id, name, description) VALUES (83, 'Geocaching', '');
-- INSERT INTO activities (park_id, name, description) VALUES (83, 'Hiking Trails', '');
-- INSERT INTO activities (park_id, name, description) VALUES (83, 'Hunting', '');
-- INSERT INTO activities (park_id, name, description) VALUES (83, 'Metal Detecting', '');
-- INSERT INTO activities (park_id, name, description) VALUES (83, 'Picnicking', '');

-- INSERT INTO parks (id, name, state_code, latitude, longitude) VALUES (84, 'Nauvoo', 'IL', 40.545, -91.385);
-- INSERT INTO activities (park_id, name, description) VALUES (84, 'Boating', '');
-- INSERT INTO activities (park_id, name, description) VALUES (84, 'Camping', '');
-- INSERT INTO activities (park_id, name, description) VALUES (84, 'Cross Country Skiing', '');
-- INSERT INTO activities (park_id, name, description) VALUES (84, 'Fishing', '');
-- INSERT INTO activities (park_id, name, description) VALUES (84, 'Hiking Trails', '');
-- INSERT INTO activities (park_id, name, description) VALUES (84, 'Museum', '');
-- INSERT INTO activities (park_id, name, description) VALUES (84, 'Picnicking', '');
-- INSERT INTO activities (park_id, name, description) VALUES (84, 'Sleding', '');

-- INSERT INTO parks (id, name, state_code, latitude, longitude) VALUES (85, 'Newton Lake State Fish and Wildlife Area', 'IL', 38.922, -88.305);
-- INSERT INTO activities (park_id, name, description) VALUES (85, 'Boating', '');
-- INSERT INTO activities (park_id, name, description) VALUES (85, 'Cross Country Skiing', '');
-- INSERT INTO activities (park_id, name, description) VALUES (85, 'Equestrian Trails', '');
-- INSERT INTO activities (park_id, name, description) VALUES (85, 'Fishing', '');
-- INSERT INTO activities (park_id, name, description) VALUES (85, 'Hiking Trails', '');
-- INSERT INTO activities (park_id, name, description) VALUES (85, 'Hunting', '');
-- INSERT INTO activities (park_id, name, description) VALUES (85, 'Metal Detecting', '');
-- INSERT INTO activities (park_id, name, description) VALUES (85, 'Mountain Bike Trails', '');
-- INSERT INTO activities (park_id, name, description) VALUES (85, 'Shelter Reservations', '');

-- INSERT INTO parks (id, name, state_code, latitude, longitude) VALUES (86, 'North Point Marina State Recreation Area', 'IL', 42.482, -87.806);
-- INSERT INTO activities (park_id, name, description) VALUES (86, 'Bike Trails', '');
-- INSERT INTO activities (park_id, name, description) VALUES (86, 'Boating', '');
-- INSERT INTO activities (park_id, name, description) VALUES (86, 'Fishing', '');
-- INSERT INTO activities (park_id, name, description) VALUES (86, 'Hiking Trails', '');
-- INSERT INTO activities (park_id, name, description) VALUES (86, 'Metal Detecting', '');
-- INSERT INTO activities (park_id, name, description) VALUES (86, 'SCUBA Diving', '');
-- INSERT INTO activities (park_id, name, description) VALUES (86, 'Swimming', '');

-- INSERT INTO parks (id, name, state_code, latitude, longitude) VALUES (87, 'Peabody River King', 'IL', 38.32097, -89.849266);
-- INSERT INTO activities (park_id, name, description) VALUES (87, 'Fishing', '');
-- INSERT INTO activities (park_id, name, description) VALUES (87, 'Hunting', '');
-- INSERT INTO activities (park_id, name, description) VALUES (87, 'Wildlife', '');

-- INSERT INTO parks (id, name, state_code, latitude, longitude) VALUES (88, 'Pere Marquette State Park', 'IL', 38.973, -90.543);

-- INSERT INTO parks (id, name, state_code, latitude, longitude) VALUES (89, 'Piney Creek Ravine State Natural Area', 'IL', 37.89, -89.638);
-- INSERT INTO activities (park_id, name, description) VALUES (89, 'Hiking', '');
-- INSERT INTO activities (park_id, name, description) VALUES (89, 'Rock Art', '');

-- INSERT INTO parks (id, name, state_code, latitude, longitude) VALUES (90, 'Powerton Lake State Fish & Wildlife Area', 'IL', 40.5385, -89.70085);

-- INSERT INTO parks (id, name, state_code, latitude, longitude) VALUES (91, 'Prophetstown State Park', 'IL', 41.672, -89.927);
-- INSERT INTO activities (park_id, name, description) VALUES (91, 'Boating', '');
-- INSERT INTO activities (park_id, name, description) VALUES (91, 'Camping', '');
-- INSERT INTO activities (park_id, name, description) VALUES (91, 'Fishing', '');
-- INSERT INTO activities (park_id, name, description) VALUES (91, 'Hiking Trails', '');
-- INSERT INTO activities (park_id, name, description) VALUES (91, 'Horseshoe Court', '');
-- INSERT INTO activities (park_id, name, description) VALUES (91, 'Hunting', '');

-- INSERT INTO parks (id, name, state_code, latitude, longitude) VALUES (92, 'Pyramid State Recreation Area', 'IL', 38.006, -89.417);
-- INSERT INTO activities (park_id, name, description) VALUES (92, 'Archery Range', '');
-- INSERT INTO activities (park_id, name, description) VALUES (92, 'Boating', '');
-- INSERT INTO activities (park_id, name, description) VALUES (92, 'Camping', '');
-- INSERT INTO activities (park_id, name, description) VALUES (92, 'Equestrian Trails', '');
-- INSERT INTO activities (park_id, name, description) VALUES (92, 'Fishing', '');
-- INSERT INTO activities (park_id, name, description) VALUES (92, 'Hiking Trails', '');
-- INSERT INTO activities (park_id, name, description) VALUES (92, 'Hunting', '');
-- INSERT INTO activities (park_id, name, description) VALUES (92, 'Metal Detecting', '');
-- INSERT INTO activities (park_id, name, description) VALUES (92, 'Mountain Bike Trails', '');

-- INSERT INTO parks (id, name, state_code, latitude, longitude) VALUES (93, 'Ramsey Lake State Recreation Area', 'IL', 39.16, -89.125);
-- INSERT INTO activities (park_id, name, description) VALUES (93, 'Boating', '');
-- INSERT INTO activities (park_id, name, description) VALUES (93, 'Camping', '');
-- INSERT INTO activities (park_id, name, description) VALUES (93, 'Equestrian Trails', '');
-- INSERT INTO activities (park_id, name, description) VALUES (93, 'Fishing', '');
-- INSERT INTO activities (park_id, name, description) VALUES (93, 'Hiking Trails', '');
-- INSERT INTO activities (park_id, name, description) VALUES (93, 'Hunting', '');
-- INSERT INTO activities (park_id, name, description) VALUES (93, 'Metal Detecting', '');
-- INSERT INTO activities (park_id, name, description) VALUES (93, 'Shelter Reservations', '');
-- INSERT INTO activities (park_id, name, description) VALUES (93, 'Snowmobile Trails', '');

-- INSERT INTO parks (id, name, state_code, latitude, longitude) VALUES (94, 'Randolph County State Recreation Area', 'IL', 37.968, -89.802);
-- INSERT INTO activities (park_id, name, description) VALUES (94, 'Boating', '');
-- INSERT INTO activities (park_id, name, description) VALUES (94, 'Camping', '');
-- INSERT INTO activities (park_id, name, description) VALUES (94, 'Cross Country Skiing', '');
-- INSERT INTO activities (park_id, name, description) VALUES (94, 'Dog Training', '');
-- INSERT INTO activities (park_id, name, description) VALUES (94, 'Equestrian Trails', '');
-- INSERT INTO activities (park_id, name, description) VALUES (94, 'Fishing', '');
-- INSERT INTO activities (park_id, name, description) VALUES (94, 'Geocaching', '');
-- INSERT INTO activities (park_id, name, description) VALUES (94, 'Hiking Trails', '');
-- INSERT INTO activities (park_id, name, description) VALUES (94, 'Hunting', '');
-- INSERT INTO activities (park_id, name, description) VALUES (94, 'Metal Detecting', '');
-- INSERT INTO activities (park_id, name, description) VALUES (94, 'Shelter Reservations', '');

-- INSERT INTO parks (id, name, state_code, latitude, longitude) VALUES (95, 'Ray Norbut', 'IL', 39.109, -90.725);

-- INSERT INTO parks (id, name, state_code, latitude, longitude) VALUES (96, 'Red Hills State Park', 'IL', 38.725, -87.843);
-- INSERT INTO activities (park_id, name, description) VALUES (96, 'Bike Trails', '');
-- INSERT INTO activities (park_id, name, description) VALUES (96, 'Boating', '');
-- INSERT INTO activities (park_id, name, description) VALUES (96, 'Camping', '');
-- INSERT INTO activities (park_id, name, description) VALUES (96, 'Cross Country Skiing', '');
-- INSERT INTO activities (park_id, name, description) VALUES (96, 'Equestrian Trails', '');
-- INSERT INTO activities (park_id, name, description) VALUES (96, 'Fishing', '');
-- INSERT INTO activities (park_id, name, description) VALUES (96, 'Geocaching', '');
-- INSERT INTO activities (park_id, name, description) VALUES (96, 'Hiking Trails', '');
-- INSERT INTO activities (park_id, name, description) VALUES (96, 'Hunting', '');
-- INSERT INTO activities (park_id, name, description) VALUES (96, 'Mountain Bike Trails', '');
-- INSERT INTO activities (park_id, name, description) VALUES (96, 'Shelter Reservations', '');

-- INSERT INTO parks (id, name, state_code, latitude, longitude) VALUES (97, 'Rice Lake SFWA', 'IL', 40.463, -89.933);
-- INSERT INTO activities (park_id, name, description) VALUES (97, 'Camping', '');
-- INSERT INTO activities (park_id, name, description) VALUES (97, 'Fishing', '');
-- INSERT INTO activities (park_id, name, description) VALUES (97, 'Hiking Trails', '');
-- INSERT INTO activities (park_id, name, description) VALUES (97, 'Hunting', '');
-- INSERT INTO activities (park_id, name, description) VALUES (97, 'Picnicking', '');

-- INSERT INTO parks (id, name, state_code, latitude, longitude) VALUES (98, 'Rock Cut State Park', 'IL', 42.342, -88.973);
-- INSERT INTO activities (park_id, name, description) VALUES (98, 'Bike Trails', '');
-- INSERT INTO activities (park_id, name, description) VALUES (98, 'Boating', '');
-- INSERT INTO activities (park_id, name, description) VALUES (98, 'Camping', '');
-- INSERT INTO activities (park_id, name, description) VALUES (98, 'Cross Country Skiing', '');
-- INSERT INTO activities (park_id, name, description) VALUES (98, 'Dog Training', '');
-- INSERT INTO activities (park_id, name, description) VALUES (98, 'Equestrian Trails', '');
-- INSERT INTO activities (park_id, name, description) VALUES (98, 'Fishing', '');
-- INSERT INTO activities (park_id, name, description) VALUES (98, 'Geocaching', '');
-- INSERT INTO activities (park_id, name, description) VALUES (98, 'Hiking Trails', '');
-- INSERT INTO activities (park_id, name, description) VALUES (98, 'Hunting', '');
-- INSERT INTO activities (park_id, name, description) VALUES (98, 'Metal Detecting', '');
-- INSERT INTO activities (park_id, name, description) VALUES (98, 'Mountain Bike Trails', '');
-- INSERT INTO activities (park_id, name, description) VALUES (98, 'Shelter Reservations', '');
-- INSERT INTO activities (park_id, name, description) VALUES (98, 'Swimming', '');

-- INSERT INTO parks (id, name, state_code, latitude, longitude) VALUES (99, 'Rock Island Trail State Park', 'IL', 40.966, -89.745);
-- INSERT INTO activities (park_id, name, description) VALUES (99, 'Bike Trails', '');
-- INSERT INTO activities (park_id, name, description) VALUES (99, 'Camping', '');
-- INSERT INTO activities (park_id, name, description) VALUES (99, 'Cross Country Skiing', '');
-- INSERT INTO activities (park_id, name, description) VALUES (99, 'Hiking Trails', '');
-- INSERT INTO activities (park_id, name, description) VALUES (99, 'Picnicking', '');
-- INSERT INTO activities (park_id, name, description) VALUES (99, 'Snowmobile Trails', '');

-- INSERT INTO parks (id, name, state_code, latitude, longitude) VALUES (100, 'Saline County SFWA', 'IL', 37.689, -88.39);
-- INSERT INTO activities (park_id, name, description) VALUES (100, 'Boating', '');
-- INSERT INTO activities (park_id, name, description) VALUES (100, 'Camping', '');
-- INSERT INTO activities (park_id, name, description) VALUES (100, 'Horseback Riding', '');
-- INSERT INTO activities (park_id, name, description) VALUES (100, 'Fishing', '');
-- INSERT INTO activities (park_id, name, description) VALUES (100, 'Hiking', '');
-- INSERT INTO activities (park_id, name, description) VALUES (100, 'Hunting', '');

-- INSERT INTO parks (id, name, state_code, latitude, longitude) VALUES (101, 'Sam Dale Lake State Fish and Wildlife Area', 'IL', 38.536, -88.585);
-- INSERT INTO activities (park_id, name, description) VALUES (101, 'Boating', '');
-- INSERT INTO activities (park_id, name, description) VALUES (101, 'Camping', '');
-- INSERT INTO activities (park_id, name, description) VALUES (101, 'Cross Country Skiing', '');
-- INSERT INTO activities (park_id, name, description) VALUES (101, 'Equestrian Trails', '');
-- INSERT INTO activities (park_id, name, description) VALUES (101, 'Fishing', '');
-- INSERT INTO activities (park_id, name, description) VALUES (101, 'Hiking Trails', '');
-- INSERT INTO activities (park_id, name, description) VALUES (101, 'Hunting', '');
-- INSERT INTO activities (park_id, name, description) VALUES (101, 'Metal Detecting', '');
-- INSERT INTO activities (park_id, name, description) VALUES (101, 'Shelter Reservations', '');

-- INSERT INTO parks (id, name, state_code, latitude, longitude) VALUES (102, 'Sam Parr SFWA', 'IL', 39.011, -88.119);
-- INSERT INTO activities (park_id, name, description) VALUES (102, 'Boating', '');
-- INSERT INTO activities (park_id, name, description) VALUES (102, 'Camping', '');
-- INSERT INTO activities (park_id, name, description) VALUES (102, 'Canoeing', '');
-- INSERT INTO activities (park_id, name, description) VALUES (102, 'Equestrian Trails', '');
-- INSERT INTO activities (park_id, name, description) VALUES (102, 'Fishing', '');
-- INSERT INTO activities (park_id, name, description) VALUES (102, 'Hiking Trails', '');
-- INSERT INTO activities (park_id, name, description) VALUES (102, 'Hunting', '');

-- INSERT INTO parks (id, name, state_code, latitude, longitude) VALUES (103, 'Sand Ridge State Forest', 'IL', 40.401, -89.879);
-- INSERT INTO activities (park_id, name, description) VALUES (103, 'Archery Range', '');
-- INSERT INTO activities (park_id, name, description) VALUES (103, 'Camping', '');
-- INSERT INTO activities (park_id, name, description) VALUES (103, 'Cross Country Skiing', '');
-- INSERT INTO activities (park_id, name, description) VALUES (103, 'Dog Training', '');
-- INSERT INTO activities (park_id, name, description) VALUES (103, 'Equestrian Trails', '');
-- INSERT INTO activities (park_id, name, description) VALUES (103, 'Geocaching', '');
-- INSERT INTO activities (park_id, name, description) VALUES (103, 'Hiking Trails', '');
-- INSERT INTO activities (park_id, name, description) VALUES (103, 'Hunting', '');
-- INSERT INTO activities (park_id, name, description) VALUES (103, 'Picnicking', '');
-- INSERT INTO activities (park_id, name, description) VALUES (103, 'Snowmobile Trails', '');

-- INSERT INTO parks (id, name, state_code, latitude, longitude) VALUES (104, 'Sanganois State Fish & Wildlife Area', 'IL', 40.09345, -90.29089);

-- INSERT INTO parks (id, name, state_code, latitude, longitude) VALUES (105, 'Sangchris Lake State Park', 'IL', 39.656, -89.487);
-- INSERT INTO activities (park_id, name, description) VALUES (105, 'Archery Range', '');
-- INSERT INTO activities (park_id, name, description) VALUES (105, 'Boating', '');
-- INSERT INTO activities (park_id, name, description) VALUES (105, 'Camping', '');
-- INSERT INTO activities (park_id, name, description) VALUES (105, 'Dog Training', '');
-- INSERT INTO activities (park_id, name, description) VALUES (105, 'Equestrian Trails', '');
-- INSERT INTO activities (park_id, name, description) VALUES (105, 'Fishing', '');
-- INSERT INTO activities (park_id, name, description) VALUES (105, 'Hiking Trails', '');
-- INSERT INTO activities (park_id, name, description) VALUES (105, 'Hunting', '');
-- INSERT INTO activities (park_id, name, description) VALUES (105, 'Metal Detecting', '');
-- INSERT INTO activities (park_id, name, description) VALUES (105, 'Shelter Reservations', '');
-- INSERT INTO activities (park_id, name, description) VALUES (105, 'Snowmobile Trails', '');

-- INSERT INTO parks (id, name, state_code, latitude, longitude) VALUES (106, 'Shabbona Lake State Recreation Area', 'IL', 41.733, -88.865);
-- INSERT INTO activities (park_id, name, description) VALUES (106, 'Boating', '');
-- INSERT INTO activities (park_id, name, description) VALUES (106, 'Camping', '');
-- INSERT INTO activities (park_id, name, description) VALUES (106, 'Cross Country Skiing', '');
-- INSERT INTO activities (park_id, name, description) VALUES (106, 'Dog Training', '');
-- INSERT INTO activities (park_id, name, description) VALUES (106, 'Fishing', '');
-- INSERT INTO activities (park_id, name, description) VALUES (106, 'Hiking Trails', '');
-- INSERT INTO activities (park_id, name, description) VALUES (106, 'Hunting', '');
-- INSERT INTO activities (park_id, name, description) VALUES (106, 'Shelter Reservations', '');
-- INSERT INTO activities (park_id, name, description) VALUES (106, 'Snowmobile Trails', '');

-- INSERT INTO parks (id, name, state_code, latitude, longitude) VALUES (107, 'Shelbyville State Fish and Wildlife Area', 'IL', 39.634, -88.708);
-- INSERT INTO activities (park_id, name, description) VALUES (107, 'Archery Range', '');
-- INSERT INTO activities (park_id, name, description) VALUES (107, 'Boating', '');
-- INSERT INTO activities (park_id, name, description) VALUES (107, 'Dog Training', '');
-- INSERT INTO activities (park_id, name, description) VALUES (107, 'Fishing', '');
-- INSERT INTO activities (park_id, name, description) VALUES (107, 'Hiking Trails', '');
-- INSERT INTO activities (park_id, name, description) VALUES (107, 'Hunting', '');

-- INSERT INTO parks (id, name, state_code, latitude, longitude) VALUES (108, 'Sielbeck Forest SNA', 'IL', 37.276, 88.849);

-- INSERT INTO parks (id, name, state_code, latitude, longitude) VALUES (109, 'Siloam Springs State Park', 'IL', 39.894, -90.93);
-- INSERT INTO activities (park_id, name, description) VALUES (109, 'Archery Range', '');
-- INSERT INTO activities (park_id, name, description) VALUES (109, 'Boating', '');
-- INSERT INTO activities (park_id, name, description) VALUES (109, 'Camping', '');
-- INSERT INTO activities (park_id, name, description) VALUES (109, 'Equestrian Trails', '');
-- INSERT INTO activities (park_id, name, description) VALUES (109, 'Fishing', '');
-- INSERT INTO activities (park_id, name, description) VALUES (109, 'Geocaching', '');
-- INSERT INTO activities (park_id, name, description) VALUES (109, 'Hiking Trails', '');
-- INSERT INTO activities (park_id, name, description) VALUES (109, 'Hunting', '');
-- INSERT INTO activities (park_id, name, description) VALUES (109, 'SCUBA Diving', '');
-- INSERT INTO activities (park_id, name, description) VALUES (109, 'Shelter Reservations', '');

-- INSERT INTO parks (id, name, state_code, latitude, longitude) VALUES (110, 'Silver Springs State Fish and Wildlife Area', 'IL', 41.626, -88.518);
-- INSERT INTO activities (park_id, name, description) VALUES (110, 'Archery Range', '');
-- INSERT INTO activities (park_id, name, description) VALUES (110, 'Boating', '');
-- INSERT INTO activities (park_id, name, description) VALUES (110, 'Camping', '');
-- INSERT INTO activities (park_id, name, description) VALUES (110, 'Canoeing', '');
-- INSERT INTO activities (park_id, name, description) VALUES (110, 'Cross Country Skiing', '');
-- INSERT INTO activities (park_id, name, description) VALUES (110, 'Dog Training', '');
-- INSERT INTO activities (park_id, name, description) VALUES (110, 'Equestrian Trails', '');
-- INSERT INTO activities (park_id, name, description) VALUES (110, 'Fishing', '');
-- INSERT INTO activities (park_id, name, description) VALUES (110, 'Geocaching', '');
-- INSERT INTO activities (park_id, name, description) VALUES (110, 'Hiking Trails', '');
-- INSERT INTO activities (park_id, name, description) VALUES (110, 'Hunting', '');
-- INSERT INTO activities (park_id, name, description) VALUES (110, 'Snowmobile Trails', '');

-- INSERT INTO parks (id, name, state_code, latitude, longitude) VALUES (111, 'Snakeden Hollow SFWA', 'IL', 41.033, -90.07);
-- INSERT INTO activities (park_id, name, description) VALUES (111, 'Boats', '');
-- INSERT INTO activities (park_id, name, description) VALUES (111, 'Fishing', '');
-- INSERT INTO activities (park_id, name, description) VALUES (111, 'Hunting', '');

-- INSERT INTO parks (id, name, state_code, latitude, longitude) VALUES (112, 'Spitler Woods State Natural Area', 'IL', 39.779, -88.862);
-- INSERT INTO activities (park_id, name, description) VALUES (112, 'Hiking Trails', '');
-- INSERT INTO activities (park_id, name, description) VALUES (112, 'Shelter Reservations', '');

-- INSERT INTO parks (id, name, state_code, latitude, longitude) VALUES (113, 'Spring Lake State Fish and Wildlife Area', 'IL', 40.473, -89.868);
-- INSERT INTO activities (park_id, name, description) VALUES (113, 'Archery Range', '');
-- INSERT INTO activities (park_id, name, description) VALUES (113, 'Boating', '');
-- INSERT INTO activities (park_id, name, description) VALUES (113, 'Camping', '');
-- INSERT INTO activities (park_id, name, description) VALUES (113, 'Cross Country Skiing', '');
-- INSERT INTO activities (park_id, name, description) VALUES (113, 'Fishing', '');
-- INSERT INTO activities (park_id, name, description) VALUES (113, 'Geocaching', '');
-- INSERT INTO activities (park_id, name, description) VALUES (113, 'Hiking Trails', '');
-- INSERT INTO activities (park_id, name, description) VALUES (113, 'Hunting', '');

-- INSERT INTO parks (id, name, state_code, latitude, longitude) VALUES (114, 'Starved Rock State Park', 'IL', 41.309, -88.989);
-- INSERT INTO activities (park_id, name, description) VALUES (114, 'Boating', '');
-- INSERT INTO activities (park_id, name, description) VALUES (114, 'Camping', '');
-- INSERT INTO activities (park_id, name, description) VALUES (114, 'Fishing', '');
-- INSERT INTO activities (park_id, name, description) VALUES (114, 'Hiking Trails', '');
-- INSERT INTO activities (park_id, name, description) VALUES (114, 'Hunting', '');
-- INSERT INTO activities (park_id, name, description) VALUES (114, 'Kayaking', '');

-- INSERT INTO parks (id, name, state_code, latitude, longitude) VALUES (115, 'Stephen A. Forbes SRA', 'IL', 38.709, -88.746);
-- INSERT INTO activities (park_id, name, description) VALUES (115, 'Boating', '');
-- INSERT INTO activities (park_id, name, description) VALUES (115, 'Camping', '');
-- INSERT INTO activities (park_id, name, description) VALUES (115, 'Dog Training', '');
-- INSERT INTO activities (park_id, name, description) VALUES (115, 'Equestrian Trails', '');
-- INSERT INTO activities (park_id, name, description) VALUES (115, 'Fishing', '');
-- INSERT INTO activities (park_id, name, description) VALUES (115, 'Geocaching', '');
-- INSERT INTO activities (park_id, name, description) VALUES (115, 'Hiking Trails', '');
-- INSERT INTO activities (park_id, name, description) VALUES (115, 'Hunting', '');
-- INSERT INTO activities (park_id, name, description) VALUES (115, 'Jet Skiing', '');
-- INSERT INTO activities (park_id, name, description) VALUES (115, 'Metal Detecting', '');
-- INSERT INTO activities (park_id, name, description) VALUES (115, 'Shelter Reservations', '');
-- INSERT INTO activities (park_id, name, description) VALUES (115, 'Swimming', '');
-- INSERT INTO activities (park_id, name, description) VALUES (115, 'Water Skiing', '');

-- INSERT INTO parks (id, name, state_code, latitude, longitude) VALUES (116, 'Ten Mile Creek State Fish and Wildlife Area', 'IL', 38.082, -88.625);
-- INSERT INTO activities (park_id, name, description) VALUES (116, 'Archery Range', '');
-- INSERT INTO activities (park_id, name, description) VALUES (116, 'Boating', '');
-- INSERT INTO activities (park_id, name, description) VALUES (116, 'Dog Training', '');
-- INSERT INTO activities (park_id, name, description) VALUES (116, 'Fishing', '');
-- INSERT INTO activities (park_id, name, description) VALUES (116, 'Hiking Trails', '');
-- INSERT INTO activities (park_id, name, description) VALUES (116, 'Hunting', '');
-- INSERT INTO activities (park_id, name, description) VALUES (116, 'Shooting Range', '');

-- INSERT INTO parks (id, name, state_code, latitude, longitude) VALUES (117, 'Trail of Tears State Forest', 'IL', 37.48, -89.351);
-- INSERT INTO activities (park_id, name, description) VALUES (117, 'Camping', '');
-- INSERT INTO activities (park_id, name, description) VALUES (117, 'Dog Training', '');
-- INSERT INTO activities (park_id, name, description) VALUES (117, 'Equestrian Trails', '');
-- INSERT INTO activities (park_id, name, description) VALUES (117, 'Fishing', '');
-- INSERT INTO activities (park_id, name, description) VALUES (117, 'Hiking Trails', '');
-- INSERT INTO activities (park_id, name, description) VALUES (117, 'Hunting', '');
-- INSERT INTO activities (park_id, name, description) VALUES (117, 'Metal Detecting', '');
-- INSERT INTO activities (park_id, name, description) VALUES (117, 'Shelter Reservations', '');

-- INSERT INTO parks (id, name, state_code, latitude, longitude) VALUES (118, 'Tunnel Hill State Trail', 'IL', 37.417, -88.887);
-- INSERT INTO activities (park_id, name, description) VALUES (118, 'Bike Trails', '');
-- INSERT INTO activities (park_id, name, description) VALUES (118, 'Hiking Trails', '');

-- INSERT INTO parks (id, name, state_code, latitude, longitude) VALUES (119, 'Turkey Bluffs', 'IL', 37.88137, -89.7647);

-- INSERT INTO parks (id, name, state_code, latitude, longitude) VALUES (120, 'Union County SFWA', 'IL', 37.392, -89.376);

-- INSERT INTO parks (id, name, state_code, latitude, longitude) VALUES (121, 'Volo Bog State Natural Area', 'IL', 42.351, -88.189);
-- INSERT INTO activities (park_id, name, description) VALUES (121, 'Cross Country Skiing', '');
-- INSERT INTO activities (park_id, name, description) VALUES (121, 'Hiking Trails', '');
-- INSERT INTO activities (park_id, name, description) VALUES (121, 'Hunting', '');

-- INSERT INTO parks (id, name, state_code, latitude, longitude) VALUES (122, 'Walnut Point State Park', 'IL', 39.704, -88.029);
-- INSERT INTO activities (park_id, name, description) VALUES (122, 'Boating', '');
-- INSERT INTO activities (park_id, name, description) VALUES (122, 'Camping', '');
-- INSERT INTO activities (park_id, name, description) VALUES (122, 'Fishing', '');
-- INSERT INTO activities (park_id, name, description) VALUES (122, 'Geocaching', '');
-- INSERT INTO activities (park_id, name, description) VALUES (122, 'Hiking Trails', '');
-- INSERT INTO activities (park_id, name, description) VALUES (122, 'Hunting', '');
-- INSERT INTO activities (park_id, name, description) VALUES (122, 'Shelter Reservations', '');

-- INSERT INTO parks (id, name, state_code, latitude, longitude) VALUES (123, 'Washington County State Recreation Area', 'IL', 38.281, -89.364);
-- INSERT INTO activities (park_id, name, description) VALUES (123, 'Archery Range', '');
-- INSERT INTO activities (park_id, name, description) VALUES (123, 'Boating', '');
-- INSERT INTO activities (park_id, name, description) VALUES (123, 'Camping', '');
-- INSERT INTO activities (park_id, name, description) VALUES (123, 'Dog Training', '');
-- INSERT INTO activities (park_id, name, description) VALUES (123, 'Fishing', '');
-- INSERT INTO activities (park_id, name, description) VALUES (123, 'Hiking Trails', '');
-- INSERT INTO activities (park_id, name, description) VALUES (123, 'Hunting', '');
-- INSERT INTO activities (park_id, name, description) VALUES (123, 'Metal Detecting', '');
-- INSERT INTO activities (park_id, name, description) VALUES (123, 'Picnicking', '');

-- INSERT INTO parks (id, name, state_code, latitude, longitude) VALUES (124, 'Wayne Fitzgerrell State Recreation Area', 'IL', 38.092, -88.949);
-- INSERT INTO activities (park_id, name, description) VALUES (124, 'Bike Trails', '');
-- INSERT INTO activities (park_id, name, description) VALUES (124, 'Boating', '');
-- INSERT INTO activities (park_id, name, description) VALUES (124, 'Camping', '');
-- INSERT INTO activities (park_id, name, description) VALUES (124, 'Fishing', '');
-- INSERT INTO activities (park_id, name, description) VALUES (124, 'Geocaching', '');
-- INSERT INTO activities (park_id, name, description) VALUES (124, 'Hiking Trails', '');
-- INSERT INTO activities (park_id, name, description) VALUES (124, 'Hunting', '');
-- INSERT INTO activities (park_id, name, description) VALUES (124, 'Jet Skiing', '');
-- INSERT INTO activities (park_id, name, description) VALUES (124, 'Metal Detecting', '');
-- INSERT INTO activities (park_id, name, description) VALUES (124, 'Shelter Reservations', '');
-- INSERT INTO activities (park_id, name, description) VALUES (124, 'Swimming', '');
-- INSERT INTO activities (park_id, name, description) VALUES (124, 'Water Skiing', '');

-- INSERT INTO parks (id, name, state_code, latitude, longitude) VALUES (125, 'Weinberg-King State Fish and Wildlife Area', 'IL', 40.227, -90.899);
-- INSERT INTO activities (park_id, name, description) VALUES (125, 'Archery Range', '');
-- INSERT INTO activities (park_id, name, description) VALUES (125, 'Camping', '');
-- INSERT INTO activities (park_id, name, description) VALUES (125, 'Cross Country Skiing', '');
-- INSERT INTO activities (park_id, name, description) VALUES (125, 'Dog Training', '');
-- INSERT INTO activities (park_id, name, description) VALUES (125, 'Equestrian Trails', '');
-- INSERT INTO activities (park_id, name, description) VALUES (125, 'Fishing', '');
-- INSERT INTO activities (park_id, name, description) VALUES (125, 'Geocaching', '');
-- INSERT INTO activities (park_id, name, description) VALUES (125, 'Hiking Trails', '');
-- INSERT INTO activities (park_id, name, description) VALUES (125, 'Hunting', '');
-- INSERT INTO activities (park_id, name, description) VALUES (125, 'Metal Detecting', '');
-- INSERT INTO activities (park_id, name, description) VALUES (125, 'Shelter Reservations', '');
-- INSERT INTO activities (park_id, name, description) VALUES (125, 'Snowmobile Trails', '');

-- INSERT INTO parks (id, name, state_code, latitude, longitude) VALUES (126, 'Weldon Springs State Park', 'IL', 40.126, -88.925);
-- INSERT INTO activities (park_id, name, description) VALUES (126, 'Boating', '');
-- INSERT INTO activities (park_id, name, description) VALUES (126, 'Camping', '');
-- INSERT INTO activities (park_id, name, description) VALUES (126, 'Cross Country Skiing', '');
-- INSERT INTO activities (park_id, name, description) VALUES (126, 'Fishing', '');
-- INSERT INTO activities (park_id, name, description) VALUES (126, 'Hiking Trails', '');
-- INSERT INTO activities (park_id, name, description) VALUES (126, 'Shelter Reservations', '');

-- INSERT INTO parks (id, name, state_code, latitude, longitude) VALUES (127, 'White Pines Forest State Park', 'IL', 41.993, -89.465);
-- INSERT INTO activities (park_id, name, description) VALUES (127, 'Camping', '');
-- INSERT INTO activities (park_id, name, description) VALUES (127, 'Cross Country Skiing', '');
-- INSERT INTO activities (park_id, name, description) VALUES (127, 'Fishing', '');
-- INSERT INTO activities (park_id, name, description) VALUES (127, 'Hiking Trails', '');
-- INSERT INTO activities (park_id, name, description) VALUES (127, 'Hunting', '');
-- INSERT INTO activities (park_id, name, description) VALUES (127, 'Shelter Reservations', '');
-- INSERT INTO activities (park_id, name, description) VALUES (127, 'Discover White Pines Lodge', '');

-- INSERT INTO parks (id, name, state_code, latitude, longitude) VALUES (128, 'William G. Stratton State Park', 'IL', 41.355, -88.418);

-- INSERT INTO parks (id, name, state_code, latitude, longitude) VALUES (129, 'William W. Powers State Recreation Area', 'IL', 41.66, -87.539);
-- INSERT INTO activities (park_id, name, description) VALUES (129, 'Bike Trails', '');
-- INSERT INTO activities (park_id, name, description) VALUES (129, 'Boating', '');
-- INSERT INTO activities (park_id, name, description) VALUES (129, 'Fishing', '');
-- INSERT INTO activities (park_id, name, description) VALUES (129, 'Hiking Trails', '');
-- INSERT INTO activities (park_id, name, description) VALUES (129, 'Hunting', '');
-- INSERT INTO activities (park_id, name, description) VALUES (129, 'Metal Detecting', '');
-- INSERT INTO activities (park_id, name, description) VALUES (129, 'Shelter Reservations', '');

-- INSERT INTO parks (id, name, state_code, latitude, longitude) VALUES (130, 'Wolf Creek State Park', 'IL', 39.482, -88.689);
-- INSERT INTO activities (park_id, name, description) VALUES (130, 'Boating', '');
-- INSERT INTO activities (park_id, name, description) VALUES (130, 'Camping', '');
-- INSERT INTO activities (park_id, name, description) VALUES (130, 'Equestrian Trails', '');
-- INSERT INTO activities (park_id, name, description) VALUES (130, 'Fishing', '');
-- INSERT INTO activities (park_id, name, description) VALUES (130, 'Geocaching', '');
-- INSERT INTO activities (park_id, name, description) VALUES (130, 'Hiking Trails', '');
-- INSERT INTO activities (park_id, name, description) VALUES (130, 'Hunting', '');
-- INSERT INTO activities (park_id, name, description) VALUES (130, 'Picnicking', '');
-- INSERT INTO activities (park_id, name, description) VALUES (130, 'Snowmobile Trails', '');
-- INSERT INTO activities (park_id, name, description) VALUES (130, 'Swimming', '');

-- INSERT INTO parks (id, name, state_code, latitude, longitude) VALUES (131, 'Woodford SFWA', 'IL', 40.955, -89.429);


-- Reset sequences to continue from 132
SELECT setval('parks_id_seq', 132, false);
SELECT setval('activities_id_seq', (SELECT MAX(id) FROM activities), true);

COMMIT;

-- Inserted 131 parks